refactor: added new options and cleaned up code

diff --git a/twitchmpv b/twitchmpv
--- a/twitchmpv
+++ b/twitchmpv
@@ -1,64 +1,200 @@
 #!/usr/bin/env bash
 
-CONFIG_FILE="$HOME/.config/twitchmpv/config"
-CHANNEL=$1
-QUALITY=$2
-STREAMLINKOPTS=$3
+args() {
+
+    if [[ ! "$1" =~ ^\-.+ ]]; then
+        CHANNEL=$1
+        shift
+    fi
+
+    local options="hc:q:n:adsv"
+    local longoptions="help,config:,quality:,name:,audio-only,disown,silent,verbose"
+    local parsed_args
+    parsed_args=$(getopt -o $options --long $longoptions -n "$(basename "$0")" -- "$@")
+
+
+    eval set -- "$parsed_args"
+    while true; do
+        case $1 in
+            -h | --help)
+                usage
+                exit 0
+                ;;
+            -c | --config)
+                shift
+                CONFIG_FILE=$1
+                ;;
+            -q | --quality)
+                shift
+                QUALITY=$1
+                ;;
+            -n | --name)
+                shift
+                CHANNEL=$1
+                ;;
+            -a | --audio-only)
+                NO_VIDEO=1
+                ;;
+            -d | --disown)
+                DISOWN=1
+                ;;
+            -s | --silent)
+                SILENT=1
+                ;;
+            -v | --verbose)
+                DEBUG=1
+                ;;
+            --)
+                shift
+                # add all remaining arguments to array of arguments
+                for arg; do
+                    OPT_ARRAY+=("$arg")
+                done
+                break
+                ;;
+            *)
+                usage
+                exit 1
+                ;;
+        esac
+        shift
+    done
+}
+
+usage() {
+    cat <<EOF 
+    Usage: twitchmpv -n|--name <channel name or url> [options] -- [streamlink arguments]
+
+    Watch Twitch streams with mpv using streamlink.
+
+    Options:
+    -h, --help              Show this help message and exit
+    -c, --config            Set the path to the config file
+    -q, --quality           Set the quality of the stream
+    -n, --name              Set the name of the twitch channel, can also be a twitch url. Required.
+    -a, --audio-only        Disable video playback
+    -d, --disown            Disown the process (if you run with -v and -d, you can only kill the process manually)
+    -s, --silent            Run streamlink in silent mode
+    -v, --verbose           Print debug information
+    --                      Pass additional arguments to streamlink
+EOF
+}
+
+error() {
+    echo "Error: $*" >&2
+    exit 1
+}
+
+info() {
+    if [ "$DEBUG" == 1 ]; then
+        echo "Info: $*" >&2
+    fi
+}
+
+check_dependencies() {
+    if ! [ -x "$(command -v streamlink)" ]; then
+        error "streamlink is not installed"
+    fi
+    if ! [ -x "$(command -v mpv)" ]; then
+        error "mpv is not installed"
+    fi
+    info "Dependencies found"
+}
+
+check_config_file() {
+    if [ -z "$CONFIG_FILE" ]; then
+        CONFIG_FILE="$HOME/.config/twitchmpv/config"
+    fi
+}
+
+load_config() {
+    if [ ! -f "$CONFIG_FILE" ]; then
+        error "Config file not found: $CONFIG_FILE"
+    fi
+    info "Loading config file: $CONFIG_FILE"
+    while read -r line; do
+        if echo "$line" | grep -F = &>/dev/null; then
+            if echo "$line" | grep -E '^\s*#' &>/dev/null; then
+                continue
+            fi
+            line1=$(echo "$line" | tr -d '[:space:]')
+            varname=$(echo "$line1" | cut -d '=' -f 1)
+            config[$varname]=$(echo "$line1" | cut -d '=' -f 2-)
+        fi
+    done < "$CONFIG_FILE"
+    
+    if [ -z "$DISOWN" ]; then
+        DISOWN="${config[disown]}"
+        info "Disown set to $DISOWN"
+    fi
+    if [ -z "$NO_VIDEO" ]; then
+        NO_VIDEO="${config[noVideo]}"
+        info "No video set to $NO_VIDEO"
+    fi
+    if [ -z "$SILENT" ]; then
+        SILENT="${config[silent]}"
+        info "Silent set to $SILENT"
+    fi
+    if [ -z "$QUALITY" ]; then
+        QUALITY="${config[defaultQuality]}"
+        info "Quality set to $QUALITY"
+    fi
+}
+
+check_channel() {
+    if [ -z "$CHANNEL" ]; then
+        usage
+        error "Channel name is required"
+    fi
+    if [[ $CHANNEL == *"twitch.tv"* ]]; then
+        STREAM_URL="$CHANNEL"
+    else
+        STREAM_URL="https://www.twitch.tv/$CHANNEL"
+    fi
+    info "Channel set to $CHANNEL"
+}
+
+check_streamlink_opts() {
+    OPT_ARRAY+=(-p mpv
+               --twitch-disable-ads
+               --twitch-api-header "Authorization=OAuth ${config[twitchOauth]}"
+               --twitch-api-header "Client-Id=${config[twitchClientId]}")
+    if [ "$NO_VIDEO" == 1 ]; then
+        OPT_ARRAY+=(-a \"--no-video\")
+    fi
+    if [ "$SILENT" == 1 ]; then
+        OPT_ARRAY+=(-Q)
+    fi
+    info "Streamlink options: ${OPT_ARRAY[*]}"
+}
+
+play_stream() {
+    info "Starting streamlink..."
+    if [ "$DISOWN" == 1 ]; then
+        streamlink "${OPT_ARRAY[@]}" "$STREAM_URL" "$QUALITY" & disown
+    else
+        streamlink "${OPT_ARRAY[@]}" "$STREAM_URL" "$QUALITY"
+    fi
+}
+
+main() {
+    check_dependencies
+    check_channel
+    check_config_file
+    load_config
+    check_streamlink_opts
+    play_stream
+}
 
 typeset -A config
 config=(
     [twitchOauth]="" # Twitch OAuth token
     [twitchClientId]="" # Twitch Client ID
     [defaultQuality]="best" # Default quality
+    [disown]=0
+    [noVideo]=0
+    [silent]=0
 )
 
-usage() {
-    echo "Usage: twitchmpv <channel or url> [quality] [\"streamlink options\"]" >&2
-}
-
-error() {
-    echo "Error: $1" >&2
-    exit 1
-}
-
-if [ ! -f "$CONFIG_FILE" ]; then
-    error "Config file not found: $CONFIG_FILE"
-fi
-
-while read -r line; do
-    if echo "$line" | grep -F = &>/dev/null; then
-        if echo "$line" | grep -E '^\s*#' &>/dev/null; then
-            continue
-        fi
-        line1=$(echo "$line" | tr -d '[:space:]')
-        varname=$(echo "$line1" | cut -d '=' -f 1)
-        config[$varname]=$(echo "$line1" | cut -d '=' -f 2-)
-    fi
-done < "$CONFIG_FILE"
-
-if [ -z "$CHANNEL" ]; then
-    usage
-    exit 1
-fi
-
-if [ -z "$QUALITY" ]; then
-    QUALITY="${config[defaultQuality]}"
-fi
-
-if ! [ -x "$(command -v streamlink)" ]; then
-    error "streamlink is not installed"
-fi
-
-# if vod then accept channel as url
-# Get the stream URL
-if [[ $CHANNEL == *"twitch.tv"* ]]; then
-    STREAM_URL="$CHANNEL"
-else
-    STREAM_URL="https://www.twitch.tv/$CHANNEL"
-fi
-
-if [ -z "$STREAMLINKOPTS" ]; then
-    streamlink -p mpv --twitch-disable-ads --twitch-api-header "Authorization=OAuth ${config[twitchOauth]}" --twitch-api-header "Client-Id=${config[twitchClientId]}" "$STREAM_URL" "$QUALITY" & disown
-else
-    streamlink -p mpv --twitch-disable-ads --twitch-api-header "Authorization=OAuth ${config[twitchOauth]}" --twitch-api-header "Client-Id=${config[twitchClientId]}" "$STREAM_URL" "$QUALITY" "$STREAMLINKOPTS" & disown
-fi
+args "$@"
+main
